---
title: "R Notebook"
output: html_notebook
---

The goal of this document is to describe how the NOAA team has interpreted the ASRP restoration scenarios for the Chehalis River basin. 

# Input data

The following spreadsheet defines the three restoration scenarios that we consider in the asrp model: 

```{r}
asrp_scenarios %>%
  filter(Scenario_num %in% c('scenario_1', 'scenario_2', 'scenario_3')) %>%
  arrange(Scenario_num, GSU) %>% 
  as_tibble() 
```
This spreadsheet is adapted from a similar spreadsheet we received via email, however this one is adapted to better fit our model.

Our asrp scenario input data consist of ten columns, described here:

1. GSU: The GSU in which restoratrion actions are defined. (GSU name)
2. LW: Do restoration scenarios target large wood?  (y/n)
3. Barriers: Do restoration scenarios target barrier removal? (y/n)
4. Floodplain: Do restoration scenarios target floodplain restoration and connectivity? (y/n)
5. Beaver: Do restoration scenarios target beaver habitat or beaver dam analogs? (y/n)
6. Riparian:  Do restoration scenarios target tree growth along stream channels? (y/n)
7. rest_perc_f: What percent of the GSU will be targeted for restoration? This applies to GSUs within managed forests only (percent of GSU in decimal form)
8. rest_perc_nf: What percent of the GSU will be targeted for restoration? This applies to GSUs outside of managed forest only (percent of GSU in decimal form) 
9. primary_cr_only: Do restoration actions target only the primary creek within a GSU? (y/n)
10. Scenario_num: Which scenario does this row describe? (Scenarios 1-3)

# Scope of restoration

There are 4,295.75 km available to coho for rearing in the entire Chehalis River basin, including 3481.36 km of small stream habitat and 777.29 km of large river habitat. Additionally, under present conditions, there are 2961.45 ha of summer floodplain habitat and 3020.50 ha of winter floodplain habitat available to coho, whereas under historical conditions there were 9667.97 ha of summer habitat and 10216.43 ha of winter habitat.  

### Scenario 1

* 1208.99 km of large river and small stream rearing habitat available to coho within GSUs specified in scenario 1 (28.1% of all available large river and small stream habitat).
* 370.45 km receive beaver restoration in scenario 1 (16% of total small stream length).
* There are 866.57 ha of current summer floodplain habitat and 912.91 ha of current winter floodplain habitat within scenario 1 GSUs where floodplain restoration is proposed 
* There are 2260.63 ha of historical summer floodplain habitat and 2389 ha of historical winter floodplain habitat within scenario 1 GSUs where floodplain restoration is proposed
* 1143.98 km receive wood restoration in scenario 1 (26.6%)
* 1192.822 km receive riparian restoration in scenario 1 (27.8%)

### Scenario 2

* 1800.61 km of large river and small stream rearing habitat available to coho within GSUs specified in scenario 2 (41.9% of all available large river and small stream habitat).
* 888.22 km receive beaver restoration in scenario 2 (25.5% of total small stream length).
* There are 1317.56 ha of current summer floodplain habitat and 1363.90 ha of current winter floodplain habitat within scenario 2 GSUs where floodplain restoration is proposed
* There are 2898.57 ha of historical summer floodplain habitat and 3042.37 ha of historical winter floodplain habitat within scenario 2 GSUs where floodplain restoration is proposed
* 1777.91 km receive wood restoration in scenario 2 (41.4%)
* 1777.91 km receive riparian restoration in scenario 2 (41.4%)

### Scenario 3

* 2375.57 km of large river and small stream rearing habitat available to coho within GSUs specified in scenario 3 (55.3% of all available large river and small stream habitat).
* 1253.41 km receive beaver restoration in scenario 3 (36% of total small stream length).
* There are 1826.97 ha of current summer floodplain habitat and 1871.46 ha of current winter floodplain habitat within scenario 3 GSUs where floodplain restoration is proposed
* There are 6706.56 ha of historical summer floodplain habitat and 6905.18 ha of historical winter floodplain habitat within scenario 3 GSUs where floodplain restoration is proposed
* 2352.86 km receive wood restoration in scenario 3 (54.8%)
* 2352.86 km receive riparian restoration in scenario 3 (54.8%)

# Description of restoration actions

### Barriers

Where `Barriers == 'y'` for a particular GSU, we model the removal of all barriers (except natural barriers) within that GSU, regardless of restoration percentage.  No barriers are removed where `Barriers == 'n'`.  The removal of barriers results in a 0.78% increase in coho spawners for scenario 1, a 1.18% increase in coho spawners for scenario 2, and a 1.28% increase in coho spawners for scenario 3.  

### Large wood

Where `LW == 'y'` for a particular GSU, we model the effect of the addition of wood to that GSU based on the restoration percentage as well as the wood intensity scalar(.6).  The addition of large wood affects our model in the following ways:

1. Rearing capacity:  We apply a large wood multiplier when calculating rearing capacity in large river, backwater, small stream, and floodplain side channel habitat.  We use the following equation to calculate the wood multipler for each reach: $$woodmult = woodmult_{curr} + (woodmult_{hist} - woodmult_{curr}) * rest.percent * intensity.scalar_{wood}$$
where $woodmult_{curr}$ == 1, $rest.percent$ can be found in the asrp_scenarios spreadsheet, and $intensity.scalar_{wood}$ == .6 for all time periods.
2. Rearing productivity:  
  + For large river habitat we multiply productivity by the wood multiplier described in section `1. Rearing capacity`
  + For small stream and floodplain habitat we have different low wood and high wood productivities.  Wood restoration within a GSU brings productivity up from the low wood productivity using the following equation: $$productivity = productivity_{low.wood} + (productivity_{high.wood} - productivity_{low.wood}) * rest.percent * intensity.scalar_{wood}$$
3. Pool and riffle percentage:  Under high wood conditions we use the `reference`, or `historical` pool and riffle percentages.  Under low wood conditions, pool and riffle ratios are based on the landcover of a particular reach.  For the asrp scenarios we use the following equation to calculate pool and riffle percentages:
$$pool.perc = pool.perc_{low.wood} + (pool.perc_{high.wood} - pool.perc_{low.wood}) * rest.percent * intensity.scalar_{wood}$$ $$riffle.perc = 1 - pool.perc$$
4. Spawning: 
  + For small stream habitat we have separate `forested` and `non-forested` redd densities in reaches with slope > 1%. Under high wood scenarios we use the `forested` redd densities whereas under the low wood scenarios we only use the `forested` redd densities where the landcover is forest, and we use the `non-forested` redd densities in all other reaches. We use the following equation to calculate egg capacity under the asrp scenarios: $$egg.capacity = reach.length_{meters} * passage.percent * ((redd.density_{forested} - redd.density_{non-forested}) * rest.percent * intensity.scalar_{wood}) / 1000 * fecundity$$ 
  + For large river habitat we apply a wood scalar when calculating spawning capacity in high wood scenarios.  Large river spawning capcaity in the asrp scenarios is calculated using the following equation: $$area_{spawning} * passage.percent / redd.area * fecundity * (1 + (1 - spawning.mult_{high.wood}) * rest.perc * intensity.scalar_{wood})$$

The addition of large wood results in a 0.94% increase in coho spawners for scenario 1, a 1.16% increase in coho spawners for scenario 2, and a 1.35% increase in coho spawners for scenario 3.

### Floodplain

Where `Floodplain == 'y'` for a particular GSU, we model the effect of floodplain restoration in that GSU based on the restoration percentage as well as the floodplain intensity scalar (.3 in managed forests, .5 outside of managed forests).  The restoration of floodplain habitat affects our model in the following ways: 

1. Rearing area: $Area = Area_{current} + (Area_{historical} - Area_{current}) * rest.percent * intensity.scalar_{floodplain}$
2. side channel spawning length: $length = length_{current} + (length_{historical} - length_{current}) * rest.percent * intensity.scalar_{floodplain}$

Restoration of floodplain habitat results in a 3.18% increase in coho spawners for scenario 1, a  3.48% increase in coho spawners for scenario 2, and a 4.62% increase in coho spawners for scenario 3. 

### Beaver

Where `Beaver == 'y'` for a particular GSU, we model the effect of beaver pond additions in that GSU based on the restoration percentage as well as the beaver intensity scalar (.3).  The restoration of beaver ponds affects our model in the following ways:

1. Rearing area: We model beaver pond area using an estimate of .3 $m^2$ of beaver pond per m of small stream at present, and 3 $m^2$ of beaver pond per m of small stream historically.  Additionally, we assume that 98.6% of small stream length is currently pool/riffle habitat, whereas 1.4% of small stream length is currently beaver pond habitat.  Historically, we assume that 85% of small stream length was pool/riffle habitat, whereas 15% of small stream length was beaver pond habitat.  Where  `Beaver == 'y'` we calculate pool, riffle, and beaver pond habitat area using the following equations: 
$$Area_{pool} = Area_{reach} * pool.perc * (percent.pool.riffle_{current} - ((percent.pool.riffle_{curr} - percent.pool.riffle_{historical}) * rest.percent * intensity.scalar_{beaver}))$$
$$Area_{riffle} = Area_{reach} * (1 - pool.perc) * (percent.pool.riffle_{current} - ((percent.pool.riffle_{curr} - percent.pool.riffle_{historical}) * rest.percent * intensity.scalar_{beaver}))$$
$$Area_{beaver.pond} = (length_{reach} * pond.area.per.m_{current} / 10000) + (length_{reach} * (pond.area.per.m_{historical} - pond.area.per.m_{current}) / 10000 * rest.percent * intensity.scalar_{beaver})$$
2. Spawning:  We do not model spawning in beaver ponds therefore the addition of beaver ponds results in a decrease in egg capacity.  Where `Beaver == 'y'` we use the following equation to calculate the length of available spawning habitat in small streams:
$$length = length_{reach} * percent.pool.riffle_{current} - ((percent.pool.riffle_{current} - percent.pool.riffle_{historical}) * rest.percent * intensity.scalar_beaver)$$

Restoration of beaver pond habitat results in a 0.51% increase in spawners for scenario 1, a 0.67% increase in spawners for scenario 2 and a 0.93% increase in spawners for scenario 3.

### Riparian

Where `Riparian == 'y'` for a particular subbasin, we model tree planting and growth for the entire GSU.  If `Riparian == 'n'` we model tree growth in all reaches where there are existing trees (canopy opening angle is less than 170°).  Where no trees currently exist we do not model any planting or growth of trees.
